import { useEffect, useMemo, useState } from 'react'
import { io } from 'socket.io-client'
import { api } from './api.js'

const Icon = ({ children }) => <span className="icon" aria-hidden="true">{children}</span>
const initialQuestion = () => ({ prompt: '', mediaType: 'text', imageUrl: '', answerType: 'single', timeLimit: 20, points: 1000, options: [{ text: '', correct: true }, { text: '', correct: false }, { text: '', correct: false }, { text: '', correct: false }] })

function Logo() {
  return <button className="logo" onClick={() => location.assign('/')} aria-label="Quizy, на главную"><span>Q</span>uizy<i>!</i><small>КВИЗЫ</small></button>
}

function Shell({ user, onNavigate, onLogout, children }) {
  return <main className="app-shell"><div className="confetti" /><header><Logo /><nav><button onClick={() => onNavigate('home')}>Главная</button>{user && <button onClick={() => onNavigate('profile')}>Мои игры</button>}{user ? <button className="nav-pill" onClick={onLogout}>Выйти · {user.name}</button> : <button className="nav-pill" onClick={() => onNavigate('auth')}>Войти</button>}</nav></header>{children}<footer>Quizy © 2026 · Собирайте друзей и отвечайте ярко</footer></main>
}

function Home({ user, navigate, setJoin }) {
  const [code, setCode] = useState('')
  return <section className="screen home"><div className="hero-copy"><span className="eyebrow">ЖИВОЙ КВИЗ ДЛЯ ВАШЕЙ КОМАНДЫ</span><h1>Знания превращаются<br /><em>в приключение!</em></h1><p>Создавайте яркие викторины, зовите друзей по коду и узнайте, кто сегодня чемпион.</p></div><div className="action-grid"><article className="toy-card purple"><div className="mascot">✦<span>?</span></div><h2>Создать свой квиз</h2><p>Вопросы, картинки и настоящий игровой драйв.</p><button className="btn lime" onClick={() => navigate(user ? 'builder' : 'auth')}><Icon>✎</Icon> Создать квиз</button></article><article className="toy-card blue"><div className="mascot pink">★<span>🏆</span></div><h2>Присоединиться</h2><p>Введите шестизначный код комнаты от ведущего.</p><div className="join-row"><input aria-label="Код комнаты" maxLength="6" inputMode="numeric" placeholder="КОД ИГРЫ" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} /><button className="btn cyan" disabled={code.length !== 6} onClick={() => { setJoin({ code }); navigate('game') }}>Играть <Icon>▶</Icon></button></div></article></div><div className="feature-strip"><span>⚡ Реальное время</span><span>🎨 4 формата вопросов</span><span>🏅 Очки и рейтинг</span></div></section>
}

function Auth({ onDone }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const data = await api(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('quizy_token', data.token); onDone(data.user) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <section className="screen narrow"><article className="toy-card form-card"><div className="tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Вход</button><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Регистрация</button></div><h1>{mode === 'login' ? 'С возвращением!' : 'Новый игрок'}</h1><form onSubmit={submit}>{mode === 'register' && <label>Имя игрока<input required maxLength="80" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Как вас зовут?" /></label>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Пароль<input required minLength="6" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Минимум 6 символов" /></label>{error && <p className="error">⚠ {error}</p>}<button className="btn lime wide" disabled={busy}>{busy ? 'Загрузка…' : mode === 'login' ? 'Войти в Quizy' : 'Создать аккаунт'}</button></form></article></section>
}

function Builder({ navigate }) {
  const [quiz, setQuiz] = useState({ title: '', description: '', questions: [initialQuestion()] }); const [active, setActive] = useState(0); const [error, setError] = useState(''); const q = quiz.questions[active]
  const updateQ = (patch) => setQuiz({ ...quiz, questions: quiz.questions.map((item, i) => i === active ? { ...item, ...patch } : item) })
  const updateOption = (index, patch) => { let options = q.options.map((o, i) => i === index ? { ...o, ...patch } : o); if (patch.correct && q.answerType === 'single') options = options.map((o, i) => ({ ...o, correct: i === index })); updateQ({ options }) }
  const save = async () => { setError(''); try { const { quiz: saved } = await api('/quizzes', { method: 'POST', body: JSON.stringify(quiz) }); const { session } = await api('/sessions', { method: 'POST', body: JSON.stringify({ quizId: saved.id }) }); navigate('host', session) } catch (err) { setError(err.message) } }
  return <section className="screen builder"><aside className="question-list"><h3>Вопросы</h3>{quiz.questions.map((item, i) => <button key={i} className={active === i ? 'active' : ''} onClick={() => setActive(i)}><b>{i + 1}</b><span>{item.prompt || 'Новый вопрос'}</span></button>)}<button className="add" onClick={() => { setQuiz({ ...quiz, questions: [...quiz.questions, initialQuestion()] }); setActive(quiz.questions.length) }}>＋ Добавить</button></aside><article className="editor toy-card"><div className="builder-head"><div><span className="eyebrow">КОНСТРУКТОР</span><input className="title-input" value={quiz.title} onChange={(e) => setQuiz({ ...quiz, title: e.target.value })} placeholder="Название квиза" /></div><button className="btn lime" onClick={save}>Сохранить и запустить</button></div><label>Текст вопроса<textarea value={q.prompt} onChange={(e) => updateQ({ prompt: e.target.value })} placeholder="Например: Какая планета ближе всего к Солнцу?" /></label><div className="settings"><label>Формат<select value={q.mediaType} onChange={(e) => updateQ({ mediaType: e.target.value })}><option value="text">Текст</option><option value="image">Картинка + текст</option></select></label><label>Выбор<select value={q.answerType} onChange={(e) => updateQ({ answerType: e.target.value, options: q.options.map((o, i) => ({ ...o, correct: i === 0 })) })}><option value="single">Один ответ</option><option value="multiple">Несколько ответов</option></select></label><label>Таймер<input type="number" min="5" max="120" value={q.timeLimit} onChange={(e) => updateQ({ timeLimit: e.target.value })} /></label></div>{q.mediaType === 'image' && <label>Ссылка на изображение<input type="url" value={q.imageUrl} onChange={(e) => updateQ({ imageUrl: e.target.value })} placeholder="https://…" /></label>}<div className="answers"><h3>Варианты ответа <small>Отметьте правильные</small></h3>{q.options.map((option, i) => <div className={`answer-edit color-${i}`} key={i}><button className={option.correct ? 'check checked' : 'check'} onClick={() => updateOption(i, { correct: !option.correct })}>{option.correct ? '✓' : '○'}</button><input value={option.text} onChange={(e) => updateOption(i, { text: e.target.value })} placeholder={`Ответ ${i + 1}`} /></div>)}</div>{error && <p className="error">⚠ {error}</p>}</article></section>
}

function Host({ room, navigate }) {
  const [state, setState] = useState({ players: [], status: 'lobby' }); const [result, setResult] = useState(null); const socket = useMemo(() => io(import.meta.env.VITE_SOCKET_URL || undefined), [])
  useEffect(() => { socket.emit('host:authorize', { code: room.code, token: localStorage.getItem('quizy_token') }, (r) => r.ok && setState(r.session)); socket.on('session:state', setState); socket.on('game:finished', (r) => setResult(r)); return () => socket.disconnect() }, [room.code, socket])
  const action = () => socket.emit(state.status === 'lobby' ? 'host:start' : 'host:next', { code: room.code })
  return <section className="screen narrow"><article className="toy-card lobby"><span className="eyebrow">КОМНАТА ГОТОВА</span><h1>Код игры</h1><div className="room-code">{room.code}</div><p>Игроки вводят этот код на главной странице</p><div className="players">{state.players?.map((p) => <span key={p.id}>{p.connected ? '●' : '○'} {p.name} · {p.score}</span>)}{!state.players?.length && <em>Ждём первых игроков…</em>}</div>{result ? <Leaderboard data={result.leaderboard} /> : <button className="btn lime wide" disabled={!state.players?.length || state.status === 'question'} onClick={action}>{state.status === 'lobby' ? 'Начать игру ▶' : state.status === 'reveal' ? 'Следующий вопрос ▶' : 'Вопрос идёт…'}</button>}<button className="text-button" onClick={() => navigate('home')}>Завершить и на главную</button></article></section>
}

function Leaderboard({ data }) { return <div className="leaderboard"><h2>🏆 Лидерборд</h2>{data.map((p, i) => <div className={`rank rank-${i + 1}`} key={p.id}><b>{i + 1}</b><span>{p.name}</span><strong>{p.score}</strong></div>)}</div> }

function Game({ initialJoin, user, navigate }) {
  const [join, setJoin] = useState({ code: initialJoin?.code || '', name: user?.name || '' }); const [connected, setConnected] = useState(false); const [session, setSession] = useState(null); const [question, setQuestion] = useState(null); const [selected, setSelected] = useState([]); const [result, setResult] = useState(null); const [seconds, setSeconds] = useState(0); const [error, setError] = useState(''); const socket = useMemo(() => io(import.meta.env.VITE_SOCKET_URL || undefined, { autoConnect: false }), [])
  useEffect(() => { const rejoin = () => { const payload = socket.auth?.join; if (payload) socket.emit('session:join', payload, (r) => { if (r.ok) { localStorage.setItem(`quizy_player_${payload.code}`, r.playerId); socket.auth.join.playerId = r.playerId; setSession(r.session); setConnected(true) } }) }; socket.on('connect', rejoin); socket.on('session:state', setSession); socket.on('question:started', (data) => { setQuestion(data); setSelected([]); setResult(null) }); socket.on('question:result', setResult); socket.on('game:finished', (r) => { setResult({ ...r, finished: true }); setQuestion(null) }); return () => socket.disconnect() }, [socket])
  useEffect(() => { if (!question?.endsAt) return; const tick = () => setSeconds(Math.max(0, Math.ceil((question.endsAt - Date.now()) / 1000))); tick(); const timer = setInterval(tick, 250); return () => clearInterval(timer) }, [question])
  const connect = (e) => { e.preventDefault(); setError(''); socket.auth = { join: { ...join, token: localStorage.getItem('quizy_token'), playerId: localStorage.getItem(`quizy_player_${join.code}`) } }; const submitJoin = () => socket.emit('session:join', socket.auth.join, (r) => { if (!r.ok) return setError(r.error); localStorage.setItem(`quizy_player_${join.code}`, r.playerId); socket.auth.join.playerId = r.playerId; setSession(r.session); setConnected(true) }); if (socket.connected) submitJoin(); else socket.connect() }
  const choose = (id) => { if (question.question.answerType === 'single') setSelected([id]); else setSelected(selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id]) }
  const submit = () => socket.emit('answer:submit', { optionIds: selected }, (r) => r.ok ? setResult({ submitted: true, correct: r.correct }) : setError(r.error))
  if (!connected) return <section className="screen narrow"><article className="toy-card form-card"><h1>Войти в игру</h1><form onSubmit={connect}><label>Код комнаты<input required pattern="\d{6}" maxLength="6" value={join.code} onChange={(e) => setJoin({ ...join, code: e.target.value.replace(/\D/g, '') })} placeholder="123456" /></label><label>Имя игрока<input required value={join.name} onChange={(e) => setJoin({ ...join, name: e.target.value })} placeholder="Ваш псевдоним" /></label>{error && <p className="error">⚠ {error}</p>}<button className="btn lime wide">Присоединиться</button></form></article></section>
  if (result?.finished) return <section className="screen narrow"><article className="toy-card lobby"><Leaderboard data={result.leaderboard} /><button className="btn cyan wide" onClick={() => navigate('home')}>На главную</button></article></section>
  if (!question) return <section className="screen narrow"><article className="toy-card lobby"><div className="spinner">★</div><h1>Вы в игре!</h1><p>Ведущий скоро запустит первый вопрос.</p><div className="players">{session?.players.map((p) => <span key={p.id}>{p.name}</span>)}</div></article></section>
  return <section className="screen play"><div className="game-top"><span>Вопрос {question.index + 1} / {question.total}</span><b className={seconds <= 5 ? 'urgent' : ''}>⏱ {seconds}</b><span>Код {join.code}</span></div><article className="question-card toy-card">{question.question.imageUrl && <img src={question.question.imageUrl} alt="Иллюстрация вопроса" />}<h1>{question.question.prompt}</h1><p>{question.question.answerType === 'multiple' ? 'Можно выбрать несколько вариантов' : 'Выберите один вариант'}</p></article><div className="answer-grid">{question.question.options.map((o, i) => <button key={o.id} disabled={result?.submitted || session?.status === 'reveal'} className={`game-answer color-${i} ${selected.includes(o.id) ? 'selected' : ''} ${result?.correctOptionIds?.includes(o.id) ? 'correct' : ''}`} onClick={() => choose(o.id)}><b>{['▲', '◆', '●', '■'][i]}</b>{o.text}</button>)}</div>{result?.submitted ? <div className={`toast ${result.correct ? 'success' : ''}`}>{result.correct ? 'Верно! Отличный ответ 🎉' : 'Ответ принят — ждём остальных'}</div> : result?.leaderboard ? <div className="toast success">Раунд завершён! Ведущий готовит следующий.</div> : <button className="btn lime submit" disabled={!selected.length} onClick={submit}>Ответить</button>}</section>
}

function Profile({ navigate }) {
  const [data, setData] = useState(null); useEffect(() => { api('/profile/history').then(setData).catch(() => setData({ quizzes: [], games: [] })) }, [])
  return <section className="screen profile"><div className="hero-copy"><span className="eyebrow">ЛИЧНЫЙ КАБИНЕТ</span><h1>Мои приключения</h1></div><div className="profile-grid"><article className="toy-card"><h2>Созданные квизы</h2>{data?.quizzes.length ? data.quizzes.map((q) => <div className="history" key={q.id}><span><b>{q.title}</b><small>{q.questionCount} вопросов</small></span></div>) : <p>Здесь появятся ваши квизы.</p>}<button className="btn lime" onClick={() => navigate('builder')}>＋ Новый квиз</button></article><article className="toy-card"><h2>История игр</h2>{data?.games.length ? data.games.map((g) => <div className="history" key={g.id}><span><b>{g.playerName}</b><small>Место: {g.rank}</small></span><strong>{g.score}</strong></div>) : <p>Сыграйте первую игру — результат сохранится здесь.</p>}</article></div></section>
}

export default function App() {
  const [page, setPage] = useState('home'); const [user, setUser] = useState(null); const [context, setContext] = useState(null); const [join, setJoin] = useState(null)
  useEffect(() => { if (localStorage.getItem('quizy_token')) api('/auth/me').then((r) => setUser(r.user)).catch(() => localStorage.removeItem('quizy_token')) }, [])
  const navigate = (next, data) => { setPage(next); setContext(data || null); scrollTo(0, 0) }
  const logout = () => { localStorage.removeItem('quizy_token'); setUser(null); navigate('home') }
  return <Shell user={user} onNavigate={navigate} onLogout={logout}>{page === 'home' && <Home user={user} navigate={navigate} setJoin={setJoin} />}{page === 'auth' && <Auth onDone={(u) => { setUser(u); navigate('home') }} />}{page === 'builder' && <Builder navigate={navigate} />}{page === 'host' && <Host room={context} navigate={navigate} />}{page === 'game' && <Game initialJoin={join} user={user} navigate={navigate} />}{page === 'profile' && <Profile navigate={navigate} />}</Shell>
}
